name: tictactoe
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- ipykernel=4.8.2
- ipython=6.4.0
- nb_conda_kernels=2.1
- pytest=3.7.3
- pytest-cov=2.5.1
- pandas=0.23
- scikit-learn=0.19